* Overview

This emacs config is optimized for clojure(script) editing.  It is
also based on the idea of Spacemacs in that we have a leader key
'SPC', that prefixes our commands.

It also uses ~evil-mode~, so if Vi is your preference, then you'll be
happy. 

Finally it uses ~lispy~ which is structural editing for lispy like
files, i.e. clojure(script).  Think paredit, but not key-chords.

* Install

Once you have the cloned the repo, make a sym link to it:

: ln -s evil-lispy-emacs-init-file.git .emacs.d

ensure you have renamed your existing ~.emacs.d~ file.

* Features

Whenever you want to run a command, type ~SPC~ (spacebar) when you are
in Normal mode.  This will bring up a list of keys you can type to run
commands. 

** File navigation

When you want to open/find up a file: 

prefix: SPC

| keys | effect         |
|------+----------------|
| f f  | find/open file |

** Buffer navigation

When you want to change to a previous buffer:

prefix: SPC

| keys | effect      |
|------+-------------|
| b b  | goto buffer |

** Code folding

Code folding is collapsing or expanding your functions so you can
focus on what you are working on without the rest of the file
polluting your screen.

prefix: SPC

| keys | effect   |
|------+----------|
| o h  | hide-all |
| o s  | show-all |
