* Overview

This emacs config is optimized for clojure(script) editing.  It is
also based on the idea of Spacemacs in that we have a leader key
'SPC', that prefixes our commands.

It also uses ~evil-mode~, so if Vi is your preference, then you'll be
happy. 

Finally it uses ~lispy~ which is structural editing for lispy like
files, i.e. clojure(script).  Think paredit, but not key-chords.

* Install

Once you have the cloned the repo, make a sym link to it:

: ln -s evil-lispy-emacs-init-file.git .emacs.d

ensure you have renamed your existing ~.emacs.d~ file.

* Features

Whenever you want to run a command, type ~SPC~ (spacebar) when you are
in Normal mode.  This will bring up a list of keys you can type to run
commands. 

** File navigation

When you want to open/find up a file: 

prefix: SPC

| keys | effect         |
|------+----------------|
| f f  | find/open file |

** Buffer navigation

When you want to change to a previous buffer:

prefix: SPC

| keys | effect      |
|------+-------------|
| b b  | goto buffer |

** Code folding

Code folding is collapsing or expanding your functions so you can
focus on what you are working on without the rest of the file
polluting your screen.

prefix: SPC

| keys | effect   |
|------+----------|
| o h  | hide-all |
| o s  | show-all |

* Lispy Mode

** Getting in (and out) of lispy mode

Lispy mode is how you'll want to edit clojure files.  It offers
structural editing, which will make more sense in a minute.  To get
into lispy mode, while in a clojure(script) file, hit any of the
following keys:

| keys   | effect                           |
|--------+----------------------------------|
| [      | move to before the opening paren |
| ]      | move to after the closing paren  |

you can also use the standard i, I, a, A, o, O Vi keys.

You'll notice your cursor changes appearance when you are in lispy
mode.  To get out of lispy mode just hit the ~ESC~ key.


